=== alexanderankin/test123/plugins/XML/trunk/xml/xml-completion-info.dtd
<!ELEMENT dtd (entity-list|element-list)*>

<!ATTLIST dtd
	html (true|false) "true"
	extend CDATA #IMPLIED>

<!ELEMENT entity-list (entity)+>

<!ELEMENT entity EMPTY>
<!ATTLIST entity
	name CDATA #REQUIRED
	value CDATA #REQUIRED>

<!ELEMENT element-list (element)+>

<!ELEMENT element (attribute)*>
<!ATTLIST element
	name CDATA #REQUIRED
	empty (true|false) #REQUIRED
	html (true|false) "false">

<!ELEMENT attribute EMPTY>
<!ATTLIST attribute
	name CDATA #REQUIRED
	value CDATA #IMPLIED
	values CDATA #IMPLIED
	required (true|false) "false">

=== alexanderankin/test123/plugins/XML/trunk/xml/completion/exslt-dates-and-times-complete.xml
<?xml version="1.0"?>
<!DOCTYPE dtd SYSTEM "xml-completion-info.dtd">
<dtd>
      <element-list>
            <element name="date-format" content="">
                  <attribute name="href" type="CDATA" required="true" />
                  <attribute name="name" type="NMTOKEN" />
                  <attribute name="calendar" type="NMTOKEN" />
                  <attribute name="lang" type="NMTOKEN" />
                  <attribute name="first-day-of-week" type="(sunday|monday|tuesday|wednesday|thursday|friday|saturday)" />
            </element>
      </element-list>
</dtd>
