=== alexanderankin/test123/plugins/Console/tags/release-3-6/console/commando/commando.dtd
<!ENTITY % att-bool '( TRUE | FALSE )' >

<!ELEMENT COMMANDO ( UI | COMMANDS )+ >

<!ELEMENT UI ( TOGGLE | ENTRY | TOGGLE_ENTRY | CHOICE | CAPTION )+ >

<!ELEMENT TOGGLE EMPTY >
<!ATTLIST TOGGLE
	LABEL CDATA #REQUIRED
	VARNAME CDATA #REQUIRED
	DEFAULT %att-bool; "FALSE"
	EVAL CDATA #IMPLIED >

<!ELEMENT ENTRY EMPTY >
<!ATTLIST ENTRY
	LABEL CDATA #REQUIRED
	VARNAME CDATA #REQUIRED
	DEFAULT CDATA #IMPLIED
	EVAL CDATA #IMPLIED >

<!ELEMENT TOGGLE_ENTRY EMPTY >
<!ATTLIST TOGGLE_ENTRY
	LABEL CDATA #REQUIRED
	VARNAME CDATA #REQUIRED
	DEFAULT CDATA #IMPLIED
	EVAL CDATA #IMPLIED >

<!ELEMENT CHOICE ( OPTION+ ) >
<!ATTLIST CHOICE
	LABEL CDATA #REQUIRED
	VARNAME CDATA #REQUIRED
	DEFAULT CDATA #IMPLIED
	EVAL CDATA #IMPLIED >

<!ELEMENT OPTION EMPTY >
<!ATTLIST OPTION
	LABEL CDATA #REQUIRED
	VALUE CDATA #REQUIRED >

<!ELEMENT CAPTION ( TOGGLE | ENTRY | TOGGLE_ENTRY | CHOICE )+ >
<!ATTLIST CAPTION
	LABEL CDATA #REQUIRED >

<!ELEMENT COMMANDS ( COMMAND+ ) >

<!ELEMENT COMMAND ( #PCDATA ) >

<!ATTLIST COMMAND
	CONFIRM %att-bool; "FALSE"
	TO_BUFFER %att-bool; "FALSE"
	BUFFER_MODE CDATA "text"
	SHELL CDATA #REQUIRED >

=== alexanderankin/test123/plugins/Console/tags/release-3-3-oops/console/commando/jikes.xml
<?xml version="1.0" ?>

<!-- This was based around jikes 1.10. -->

<!DOCTYPE COMMANDO SYSTEM "commando.dtd">

<COMMANDO>
	<UI>
		<CAPTION LABEL="Source file(s)">

		<ENTRY LABEL="Source file(s)" VARNAME="source"
			EVAL="buffer.getPath()" />

		</CAPTION>

		<CAPTION LABEL="Paths">

		<ENTRY LABEL="Class path" VARNAME="classpath"
			EVAL="getBufferClassPath(buffer)" />
		<ENTRY LABEL="Output directory" VARNAME="outputpath" />

		</CAPTION>

		<CAPTION LABEL="Compilation flags">

		<TOGGLE LABEL="Generate debug info" VARNAME="debug" />
		<TOGGLE LABEL="Optimize" VARNAME="optimize" />
		<TOGGLE LABEL="Show warnings" VARNAME="warn" DEFAULT="TRUE" />
		<TOGGLE LABEL="Show deprecation" VARNAME="deprecation" DEFAULT="TRUE" />
		<TOGGLE LABEL="Pedantic warnings" VARNAME="pedantic" />
		<TOGGLE LABEL="Treat cautions as errors" VARNAME="cautions" />

		</CAPTION>
	</UI>

	<COMMANDS>
		<COMMAND SHELL="System" CONFIRM="FALSE">
			buf = new StringBuffer("jikes +E");

			if(!classpath.equals(""))
			{
				buf.append(" -classpath \"");
				buf.append(classpath);
				buf.append('"');
			}

			if(!outputpath.equals(""))
			{
				buf.append(" -d \"");
				buf.append(outputpath);
				buf.append('"');
			}

			if(debug)
				buf.append(" -g");

			if(optimize)
				buf.append(" -O");

			if(!warn)
				buf.append(" -nowarn");

			if(deprecation)
				buf.append(" -deprecation");

			if(pedantic)
				buf.append(" +P");

			buf.append(' ');
			buf.append(source);

			// return value
			buf.toString();
		</COMMAND>
	</COMMANDS>
</COMMANDO>
